### ISSUE TITLE
update function (howto via cronjob)?

### ISSUE THREAD

**Issue by mrc4tt** [dasisdormax/csgo-multiserver#1]
Hi,

How will it works to using the "update" function from the script?

If i want to update only the "main csgo files" - now where the (multiple instances) using the same symlink/shared files. 

I hope you can help!

**Comment by mrc4tt** [comment]
@dasisdormax - dunno about you are active :D

**Comment by dasisdormax** [comment]
Hello @MikkelDK,

I'll try my best to explain what the update function does. I haven't worked on the script for a while so I might get some things off ^^

When you execute `csgo-server update`, the script will first check if a new game version is available. If an update is required, the instances will shut down temporarily, the updater will perform the game update and the instances will start back up again.

You don't have to (and cannot) update the instances individually. You shouldn't have to do anything else, you only have to take care of Metamod and Sourcemod updates if you use them.

As an example, if you want to have your installation updated every night at 3 a.m. automatically, you can just add the update command to your crontab by executing `crontab -e` as the admin user and adding the line:

    0 3 * * * /path/to/csgo-server update

> @dasisdormax - dunno about you are active :D

I wrote this script to organize a local CS:GO tournament and didn't have any reason to continue developing so far. It is nice to know though that my script is helping you :) Please ask if you have any more questions or find a bug

**Comment by mrc4tt** [comment]
I found a little bug  as example with GOTV (the tv_enable 1)
Example: `TV_ENABLE="1"` on server.conf (via: /csgo-multiserver/apps/csgo/scripts) - it don't set GOTV enabled.

So i did added: tv_enable 1 (under like this):
```

# GOTV specific settings ####
(( $TV_ENABLE )) &&     cat <<-EOF >> "$AUTOEXEC_CFG"



        // -------- GOTV --------
        tv_advertize_watchable "$TV_ADVERTIZE_WATCHABLE"
        tv_autorecord "$TV_AUTORECORD"
        tv_enable 1
        tv_password "$TV_PASS"
        tv_title "$TV_TITLE"

```
As you see (( $TV_ENABLE )) - seems it will not load it. so i did entered: tv_enable 1 (on the line).

**A idea**:
I have a little idea, dunno about it can be (created - I'm not a hardcore coder, but willing to pay!) 
Demo uploader (dunno about it will be possible to make possible) - as an example, if people doing tv_record + tv_stoprecord, and want to download the demo. > and make a way (where) the demo will be uploaded (to some site. or a www folder)

**Comment by dasisdormax** [comment]
Hello again,

Thumbs up for looking into my code and trying to improve :) I'm sorry to disappoint you though, but `tv_enable 1` wasn't missing, it is just not in the autoexec.cfg but in the launch arguments (line 396) ^^ . Some commands have to be in the arguments and don't work in the autoexec.cfg (or at least it used to be this way)

For your demo upload suggestion, I do not know how to integrate this well. Besides, there are Sourcemod plugins that provide automatic demo recording and uploading. I do not know your specific use case, but you can try [Warmod](https://forums.alliedmods.net/showthread.php?t=225474https://forums.alliedmods.net/showthread.php?t=225474) with [curl](https://forums.alliedmods.net/showthread.php?t=152216) and [tEasyFTP](https://forums.alliedmods.net/showthread.php?p=1629724) as a starting point for your search.

**Comment by mrc4tt** [comment]
Hello,

Oooh. I see. just an idea. maybe to update it. :D 

I think. I will fork, and make some changes. ;) and maybe it can be (updated) here? ;-) what are you think?

**Comment by dasisdormax** [comment]
Sure, feel free to do so. I cannot promise that I can include your changes here, but it will be easier if you make several small and simple changes instead of one big one :)

**Comment by mrc4tt** [comment]
And maybe incl some tweaked server.cfg + other .cfg files like esl5on5/alias e.g? what are you think? - if it's possible? :D

**Comment by dasisdormax** [comment]
I assume you are talking about your CSGOConfigs repository. You could create a preset file with all your custom gamemode settings, I am a bit uncomfortable with adding your config files for everyone though.

I'd rather create a possibility for users to include their own configs where necessary, would you like that?

**Comment by mrc4tt** [comment]
As example yeah. I have make some cfg files, where people can use them.

E.g not all know the correct settings, with esl5on5 and such. So i did make cfg files, people can use free. :)

**Comment by mrc4tt** [comment]
btw @dasisdormax I found a weird bug.
did fix the bug! ;)

I will soon come with a PR! ;)
