### ISSUE TITLE
plugins trouble settings

### ISSUE THREAD

**Issue by blazerino** [dasisdormax/csgo-multiserver#7]
MSM is compatible whit sourcemod?

**Comment by dasisdormax** [comment]
Yes, it can launch servers running sourcemod too, but it does not do the installation for you.

You'll need to install metamod:source and sourcemod manually to each instance's csgo/addons directory and configure databases and admins as usual.

**Comment by blazerino** [comment]
I really appreciate your answer, your work is amazing. I´m actually running seven instance´s with one base installation, maybe that is the limit. 30 GB to run seven servers with plugins included, really incredible.
Congrats and thanks to you dude.

**Comment by fazdamoa** [comment]
Did you have to do any special config to get addons working? I have installed metamod into the individual server folders and even tried the base server folder without success...just doesn't seem to load the add ons.

**Comment by dasisdormax** [comment]
nope, you just extract metamod / sourcemod in the instance's csgo directory, as you would with any csgo server.

However, I tried a clean install again and got the same problem. If you run an Ubuntu / Debian server, try installing the 'lib32stdc++6' package, that fixed it for me. I'll update the readme accordingly. Thanks for your find!
