### ISSUE TITLE
I can't seem to enable RCON ?

### ISSUE THREAD

**Issue by android-imdad** [dasisdormax/csgo-multiserver#8]
any idea how I can do it

**Comment by dasisdormax** [comment]
You can enable RCON with the variables RCON_ENABLED and RCON_PASS, by adding them
a) to the start command with `RCON_ENABLED=1 RCON_PASS='your_rcon_password' csgo-server start`
b) to the front of your instance's server.conf (put RCON_ENABLED=1 and RCON_PASS='***' on separate lines and make sure there are no spaces in front or after the equals sign).

Hope it helps :)

**Comment by android-imdad** [comment]
Nice, thanks!
