### ISSUE TITLE
Server instance crush after 5th

### ISSUE THREAD

**Issue by Amourmort** [dasisdormax/csgo-multiserver#9]
5 instances of CS:GO server are running, but I can't launch 6th. In log:

`WARNING: UDP_OpenSocket: unable to bind socket`
`Couldn't allocate any server IP port, tried 1 addresses localhostTue 18 May 2021 08:05:40 PM EEST: Server Quit`
Config is almost the same, only different maps.
I don't know how to debug that. Grateful for your help.

**Comment by dasisdormax** [comment]
Hello,

which ports are you using for your servers?

**Comment by Amourmort** [comment]
> which ports are you using for your servers?

Hi!
All instances uses the same default port 
`PORT=${PORT-"27015"}`

If I change that number, 6th instance starts normally but clients don't see it - it doesn't appears in the LAN servers list.

**Comment by dasisdormax** [comment]
Ok. Using the same port for each instance is not supported, try using a separate port for each instance. 
I personally suggest 27015, 27115, 27215, ...

I assume CS:GO automatically tries the next ports and the 6th instance hit 27020, which is used by GOTV from the first server

**Comment by Amourmort** [comment]
Thanks, Maximilian, i will check that out tomorrow. But how clients will see that instances? As i said above, when i change the 6th instance's port to 27016 it seems running but not listed in client

**Comment by dasisdormax** [comment]
Assuming the GSLTs are set properly and the server is reachable from the internet, the servers should advertise themselves automatically so they can be seen in the server browser. I have not tried it recently though. 

You may need to set the instance's server title to make it easier to find. Also, the server browser doesn't work for servers in your local network if the port is not 27015.

Anyway, you can always connect to your server from the client with the console command `connect 10.20.30.40:27115` (replace ip and port accordingly)

**Comment by Amourmort** [comment]
> Assuming the GSLTs are set properly and the server is reachable from the internet

No, it is not. My server is for only local use yet, mb i'll set GSLT later, not now. The server browser shows 5 instances running on the same port. If I try to add an IP alias or virtual NIC with different IP on server and set different instances to different IPs using LOCAL_IP variable instances all running but browser shows nothing (why?)

I will try out to configure Linux core and so_reuseport socket option. Tell you if any success.

**Comment by dasisdormax** [comment]
Okay, now it's getting complicated. AFAIK the LAN server browser will only find servers in the same subnet and with the default port. 

You may get somewhere if you can bind your instances on different local IPs, port 27015 (for example IP=192.168.0.100, IP=192.168.0.101). The command `ss -ulpn` will show you exactly, which addresses and ports are currently used by your csgo server instances.

The rest depends on your local network structure. Good luck!
